### ISSUE TITLE
ICE whilst compiling an (possibly invalid) initialisation of struct with array member  

### ISSUE THREAD

**Issue by DontBelieveMe** [tendra/tendra#119]
### Description

This came up whilst testing TenDRA against the C89 tests in [c-testsuite/c-testsuite](https://github.com/c-testsuite/c-testsuite). Specifically this was from test [00205.c](https://github.com/c-testsuite/c-testsuite/blob/master/tests/single-exec/00205.c). The given repo program source is a heavily reduced version of that test (_heavily_ heavily reduced 😄).

Honestly I don't know if the given repo source is valid C90 but either way it probably shouldn't ICE. (Isn't it a thing to be able to zero a struct via `= { 0 };` - or maybe that's C++ or a later C version...)

#### Repo program source
```c
struct s {
  int a[1];
};

struct s c = { 0 };
```

#### CLI input/output
```console
me@pc:~/c-testsuite$ ~/tendra/obj/bin/tcc ice.c
Assertion Null pointer failed, init.c, line 212.
tcc: Error: Caught signal 6 in '/home/me/tendra/obj/libexec/tdfc2'
tcc: Error: Caught signal 6 in '/home/me/tendra/obj/libexec/tdfc2'
```

#### Stack trace
```c
#2  0x0000556707f12826 in assert_c_class (s=0x556707fc1693 "Null pointer", fn=0x556707fc2a08 "init.c", ln=212)
    at assert_def.h:26
#3  0x0000556707f12856 in check_null_c_class (p=0x0, fn=0x556707fc2a08 "init.c", ln=212) at assert_def.h:34
#4  0x0000556707f3694a in enc_init_class (bs=0x556708fe2850, e=0x556708fe3f08, ct=0x556708fe38a8) at init.c:212
#5  0x0000556707f35958 in enc_exp (bs=0x556708fe2850, e=0x556708fe3f08) at exp.c:2716
#6  0x0000556707f3a400 in enc_init_global (bs=0x556708fe2850, e=0x556708fe3f08, d=0x0, n=2147483648, t=0x556708fdb3a8)
    at init.c:1027
#7  0x0000556707f17c7d in make_tagdef (id=0x556708fe3db8, t=0x556708fdb3a8, e=0x556708fe3f08, d=0x0, var=1)
    at compile.c:793
#8  0x0000556707f19aeb in compile_variable (id=0x556708fe3db8, force=0) at compile.c:1345
#9  0x0000556707e95c20 in init_object (id=0x556708fe3db8, e=0x556708fe3f08) at initialise.c:2160
#10 0x0000556707fa3186 in ZR822 (ZIbt=0x7fff45d5c8e0, ZIt=0x7fff45d5c870, ZIds=0x7fff45d5c878, ZIs=0x7fff45d5c880,
    ZIid=0x7fff45d5c888) at syntax.act:1255
#11 0x0000556707fa2d6e in ZR948 (ZI944=0x7fff45d5c8e0, ZI945=0x7fff45d5c8e8, ZI946=0x7fff45d5c8c0,
    ZI947=0x7fff45d5c8f0, ZOe=0x7fff45d5c8f8) at syntax3.c:190
#12 0x0000556707f96fd7 in ZRdeclaration_Hseq_Hopt () at syntax1.c:1560
#13 0x0000556707f9fcbc in parse_file (ZIt=0x0, ZIds=0) at syntax2.c:2762
#14 0x0000556707f7319c in process_file () at lex.c:2000
#15 0x0000556707f95072 in process_files (files=0x556708f9c340) at main.c:936
#16 0x0000556707f95250 in main (argc=13, argv=0x7fff45d5cbb8) at main.c:1007
```

**Comment by katef** [comment]
oof, this is a great one. Also we should absolutely run that test suite in CI. Thank you!
